version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_canhbao
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_canhbao
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

  backend:
    build:
      context: ./suco/suco
      dockerfile: Dockerfile.dev
    container_name: suco_backend
    restart: always
    ports:
      - "8080:8080"

    volumes:
      - ./suco/suco:/app

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: dev

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
