# resource: CanhBaoSuCo/suco/suco/src/main/resources/application-dev.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

gemini.api.keys=${GEMINI_API_KEYS}

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
MAPBOX_PUBLIC_TOKEN=${MAPBOX_PUBLIC_TOKEN}

server.servlet.session.persistent=false