# resource: CanhBaoSuCo/suco/suco/src/main/resources/application.properties

spring.application.name=suco

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

server.max-http-header-size=10MB
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

server.tomcat.max-swallow-size=15MB
server.tomcat.max-http-form-post-size=15MB

gemini.model=${GEMINI_MODEL}
gemini.url=${GEMINI_URL}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# TẮT SQL LOG HIBERNATE
spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF