# resource: CanhBaoSuCo/suco/suco/src/main/resources/application-prod.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

jwt.secret=${JWT_SECRET}
gemini.api.keys=${GEMINI_API_KEYS}
MAPBOX_PUBLIC_TOKEN=${MAPBOX_PUBLIC_TOKEN}